name: Lint
on:
  push:
    paths-ignore:
      - '.github/workflows/*'
      - '.github/actions/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable