name: Lint
on:
  push:
    branches:
      - main
      - new
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/*'
      - '.github/actions/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable